"""FastAPI request handler for the Field-Service RAG Bot.

Exposes a single POST endpoint ``/api/chat`` that accepts a user message
together with a session ID and returns a plain-text answer generated by
the Azure OpenAI chat completions API.

Required environment variables (supplied via repository secrets):
    AZURE_OPENAI_ENDPOINT   – Azure OpenAI resource endpoint URL
    AZURE_OPENAI_API_KEY    – Azure OpenAI API key
    AZURE_OPENAI_DEPLOYMENT – Azure deployment name (model)

Usage:
    uvicorn requesthandler:app --reload
"""

import os
import logging

from fastapi import FastAPI, HTTPException
from openai import AzureOpenAI, OpenAIError
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware

# Optional: load a local .env when developing locally (install python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

MAX_TOKENS = 50

app = FastAPI(title="Field-Service RAG Bot API")

# Allow all origins for the demo phase.
# Restrict `allow_origins` to the actual front-end URL in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    """Incoming chat message from the front-end."""

    message: str
    sessionId: str


class ChatResponse(BaseModel):
    """Outgoing chat answer returned to the front-end."""

    answer: str


# remove the eager import-time check and client creation; create client on startup
_azure_client = None

@app.on_event("startup")
async def startup_event():
    """Initialize AzureOpenAI client if env vars are present; otherwise warn."""
    missing = [
        v for v in ("AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY", "AZURE_OPENAI_DEPLOYMENT")
        if not os.environ.get(v)
    ]
    if missing:
        logging.warning(
            "Missing required environment variable(s): %s. Server will start but /api/chat will return 503 until set.",
            ", ".join(missing),
        )
    else:
        global _azure_client
        _azure_client = AzureOpenAI(
            azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
            api_key=os.environ["AZURE_OPENAI_API_KEY"],
            api_version="2024-02-01",
        )
        logging.info("Azure OpenAI client initialized.")


@app.post("/api/chat", response_model=ChatResponse)
async def chat(req: ChatRequest) -> ChatResponse:
    """Handle a chat request and return an answer from the Azure OpenAI API.

    Args:
        req: The incoming request containing the user's message and a
             session identifier for future multi-turn support.

    Returns:
        A ``ChatResponse`` with the generated answer string.
    """
    if _azure_client is None:
        raise HTTPException(
            status_code=503,
            detail="Azure OpenAI client not configured. Set AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY and AZURE_OPENAI_DEPLOYMENT.",
        )
    try:
        completion = _azure_client.chat.completions.create(
            model=os.environ["AZURE_OPENAI_DEPLOYMENT"],
            messages=[{"role": "user", "content": req.message}],
            max_tokens=MAX_TOKENS,
        )
        answer = completion.choices[0].message.content or ""
        return ChatResponse(answer=answer)
    except OpenAIError as exc:
        raise HTTPException(status_code=502, detail="Azure OpenAI request failed.") from exc
