"""FastAPI request handler for the Field-Service RAG Bot.

Exposes two POST endpoints:
- ``/api/session/init`` – initialises a new chat session with the system prompt
  (no LLM call, no UI response).
- ``/api/chat`` – accepts a user message together with a session ID and returns
  a plain-text answer generated by the Azure OpenAI chat completions API.
  Full conversation history is maintained per session.

Required environment variables (supplied via repository secrets):
    AZURE_OPENAI_ENDPOINT   – Azure OpenAI resource endpoint URL
    AZURE_OPENAI_API_KEY    – Azure OpenAI API key
    AZURE_OPENAI_DEPLOYMENT – Azure deployment name (model)

Usage:
    uvicorn requesthandler:app --reload
"""

import os
import logging
from pathlib import Path
import json

from fastapi import FastAPI, HTTPException
from openai import AzureOpenAI, OpenAIError
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware

# Optional: load a local .env when developing locally (install python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

MAX_TOKENS = 51

# ---------------------------------------------------------------------------
# System prompt – loaded once at module import time from system_prompt.txt.
# Falls back to a minimal default if the file is not found.
# ---------------------------------------------------------------------------
_SYSTEM_PROMPT_PATH = Path(__file__).parent / "system_prompt.txt"
try:
    _SYSTEM_PROMPT = _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
    logging.info("System prompt loaded from %s", _SYSTEM_PROMPT_PATH)
except FileNotFoundError:
    _SYSTEM_PROMPT = "You are a helpful field service assistant."
    logging.warning(
        "system_prompt.txt not found at %s – using minimal default.",
        _SYSTEM_PROMPT_PATH,
    )

# ---------------------------------------------------------------------------
# In-memory session store: maps sessionId → list of OpenAI-style messages.
# ---------------------------------------------------------------------------
_sessions: dict[str, list[dict]] = {}

app = FastAPI(title="Field-Service RAG Bot API")

# Allow all origins for the demo phase.
# Restrict `allow_origins` to the actual front-end URL in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    """Incoming chat message from the front-end."""

    message: str
    sessionId: str


class ChatResponse(BaseModel):
    """Outgoing chat answer returned to the front-end."""

    answer: str


class SessionInitRequest(BaseModel):
    """Request body for initialising a new session."""

    sessionId: str


class SessionInitResponse(BaseModel):
    """Response returned after a session is initialised."""

    status: str
    sessionId: str


# remove the eager import-time check and client creation; create client on startup
_azure_client = None

@app.on_event("startup")
async def startup_event():
    """Initialize AzureOpenAI client if env vars are present; otherwise warn."""
    missing = [
        v for v in ("AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY", "AZURE_OPENAI_DEPLOYMENT")
        if not os.environ.get(v)
    ]
    if missing:
        logging.warning(
            "Missing required environment variable(s): %s. Server will start but /api/chat will return 503 until set.",
            ", ".join(missing),
        )
    else:
        global _azure_client
        _azure_client = AzureOpenAI(
            azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
            api_key=os.environ["AZURE_OPENAI_API_KEY"],
            api_version="2024-02-01",
        )
        logging.info("Azure OpenAI client initialized.")


@app.post("/api/session/init", response_model=SessionInitResponse)
async def session_init(req: SessionInitRequest) -> SessionInitResponse:
    """Initialise a chat session with the system prompt.

    Creates a new session entry containing only the system prompt message.
    If the session already exists it is left unchanged (idempotent).
    The LLM is **not** called; nothing is shown in the UI.

    Args:
        req: Request body containing the client-generated session ID.

    Returns:
        A ``SessionInitResponse`` with status ``"ok"`` and the session ID.
    """
    if req.sessionId not in _sessions:
        _sessions[req.sessionId] = [{"role": "system", "content": _SYSTEM_PROMPT}]
        logging.info("Session initialised: %s", req.sessionId)
    else:
        logging.info("Session already exists, skipping init: %s", req.sessionId)
    return SessionInitResponse(status="ok", sessionId=req.sessionId)


@app.post("/api/chat", response_model=ChatResponse)
async def chat(req: ChatRequest) -> ChatResponse:
    """Handle a chat request and return an answer from the Azure OpenAI API.

    Maintains full conversation history per session so the LLM has context
    from previous turns. If no session exists yet (e.g. the init endpoint was
    not called) one is created on-the-fly with the system prompt.

    Args:
        req: The incoming request containing the user's message and session ID.

    Returns:
        A ``ChatResponse`` with the generated answer string.
    """
    if _azure_client is None:
        raise HTTPException(
            status_code=503,
            detail="Azure OpenAI client not configured. Set AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY and AZURE_OPENAI_DEPLOYMENT.",
        )

    # Ensure the session exists (fallback if /api/session/init was not called)
    if req.sessionId not in _sessions:
        logging.warning("Session %s not found – creating on-the-fly.", req.sessionId)
        _sessions[req.sessionId] = [{"role": "system", "content": _SYSTEM_PROMPT}]

    history = _sessions[req.sessionId]
    history.append({"role": "user", "content": req.message})

    

    try:
        completion = _azure_client.chat.completions.create(
            model=os.environ["AZURE_OPENAI_DEPLOYMENT"],
            messages=history,
            max_tokens=MAX_TOKENS,
        )
        answer = completion.choices[0].message.content or ""
        history.append({"role": "assistant", "content": answer})
        return ChatResponse(answer=answer)
    except OpenAIError as exc:
        # Remove the user message that failed so the history stays consistent
        history.pop()
        raise HTTPException(status_code=502, detail="Azure OpenAI request failed.") from exc

