"""FastAPI request handler for the Field-Service RAG Bot.

Exposes two POST endpoints:
- ``/api/session/init`` – initialises a new chat session with the system prompt
  (no LLM call, no UI response).
- ``/api/chat`` – accepts a user message together with a session ID and returns
  a plain-text answer generated by the Azure OpenAI chat completions API.
  Full conversation history is maintained per session.

Required environment variables (supplied via repository secrets):
    AZURE_OPENAI_ENDPOINT      – Azure OpenAI resource endpoint URL
    AZURE_OPENAI_API_KEY       – Azure OpenAI API key
    AZURE_OPENAI_DEPLOYMENT    – Azure deployment name (main model)

Optional environment variables for prompt optimisation (pre-flight rewrite):
    AZURE_REWRITE_ENDPOINT     – Endpoint of the lightweight rewrite model deployment
    AZURE_REWRITE_API_KEY      – API key for the rewrite deployment
    AZURE_REWRITE_DEPLOYMENT   – Deployment name of the lightweight rewrite model
                                  (recommended: gpt-4o-mini)
    If any of these three are absent the optimisation step is silently skipped
    and the raw user message is sent to the main model unchanged.

    TODO:
    Uvicorn rausschmeißen
    Env anlegen checken
    Docker architektur schreiben


Usage:
    uvicorn requesthandler:app --reload
"""

import os
import logging
from pathlib import Path
import json
import httpx
from typing import Optional

import Context_Handler 

from fastapi import FastAPI, HTTPException
from openai import AzureOpenAI, OpenAIError
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware

# Optional: load a local .env when developing locally (install python-dotenv)
try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

MAX_TOKENS = 100
REWRITE_MAX_TOKENS = 150

# Context Handler config (optional). If not set, context lookup is skipped.
CONTEXT_HANDLER_URL = "http://localhost:5000/context"
CONTEXT_HANDLER_TOKEN = os.environ.get("CONTEXT_HANDLER_TOKEN")

# ---------------------------------------------------------------------------
# Rewrite / prompt-optimisation system instruction.
# Used by the lightweight pre-flight model to clean up user messages before
# they are forwarded to the main RAG model.
# ---------------------------------------------------------------------------
_REWRITE_SYSTEM_INSTRUCTION = (
    "You are a prompt-optimisation assistant for a Miele field-service chatbot. "
    "Your only job is to rewrite the technician's message so it is grammatically "
    "correct, clearly phrased, and well-suited for a technical documentation search. "
    "Rules:\n"
    "1. Fix all spelling and grammar mistakes.\n"
    "2. Rephrase fragments or vague notes as a precise, answerable question.\n"
    "3. Preserve all technical terms, model numbers, error codes, and part names "
    "exactly as written (e.g. F67, W1, PCB, NTC, G7310).\n"
    "4. Do NOT answer the question – return only the improved prompt.\n"
    "5. Return only the rewritten message, no explanations or meta-commentary."
)

# ---------------------------------------------------------------------------
# System prompt – loaded once at module import time from system_prompt.txt.
# Falls back to a minimal default if the file is not found.
# ---------------------------------------------------------------------------
_SYSTEM_PROMPT_PATH = Path(__file__).parent / "system_prompt.txt"
try:
    _SYSTEM_PROMPT = _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
    logging.info("System prompt loaded from %s", _SYSTEM_PROMPT_PATH)
except FileNotFoundError:
    _SYSTEM_PROMPT = "You are a helpful field service assistant."
    logging.warning(
        "system_prompt.txt not found at %s – using minimal default.",
        _SYSTEM_PROMPT_PATH,
    )

# ---------------------------------------------------------------------------
# In-memory session store: maps sessionId → list of OpenAI-style messages.
# ---------------------------------------------------------------------------
_sessions: dict[str, list[dict]] = {}

app = FastAPI(title="Field-Service RAG Bot API")

# Allow all origins for the demo phase.
# Restrict `allow_origins` to the actual front-end URL in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    """Incoming chat message from the front-end.

    Optional `model` can be provided by the frontend and is forwarded to the
    Context_Handler as a filter. It does NOT change the Azure deployment used
    for the final LLM call (that is controlled via AZURE_OPENAI_DEPLOYMENT).
    """

    message: str
    sessionId: str
    model: Optional[str] = None


class ChatResponse(BaseModel):
    """Outgoing chat answer returned to the front-end."""

    answer: str


class SessionInitRequest(BaseModel):
    """Request body for initialising a new session."""

    sessionId: str


class SessionInitResponse(BaseModel):
    """Response returned after a session is initialised."""

    status: str
    sessionId: str


# remove the eager import-time check and client creation; create client on startup
_azure_client = None
_rewrite_client = None

@app.on_event("startup")
async def startup_event():
    """Initialize AzureOpenAI clients if env vars are present; otherwise warn."""
    global _azure_client, _rewrite_client

    # --- Main model client ---
    missing = [
        v for v in ("AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_API_KEY", "AZURE_OPENAI_DEPLOYMENT")
        if not os.environ.get(v)
    ]
    if missing:
        logging.warning(
            "Missing required environment variable(s): %s. Server will start but /api/chat will return 503 until set.",
            ", ".join(missing),
        )
    else:
        _azure_client = AzureOpenAI(
            azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
            api_key=os.environ["AZURE_OPENAI_API_KEY"],
            api_version="2024-02-01",
        )
        logging.info("Azure OpenAI client initialized.")

    # --- Rewrite model client (optional) ---
    rewrite_vars = ("AZURE_REWRITE_ENDPOINT", "AZURE_REWRITE_API_KEY", "AZURE_REWRITE_DEPLOYMENT")
    missing_rewrite = [v for v in rewrite_vars if not os.environ.get(v)]
    if missing_rewrite:
        logging.warning(
            "Prompt optimisation disabled – missing rewrite env var(s): %s.",
            ", ".join(missing_rewrite),
        )
    else:
        _rewrite_client = AzureOpenAI(
            azure_endpoint=os.environ["AZURE_REWRITE_ENDPOINT"],
            api_key=os.environ["AZURE_REWRITE_API_KEY"],
            api_version="2024-02-01",
        )
        logging.info("Azure OpenAI rewrite client initialized (deployment: %s).", os.environ["AZURE_REWRITE_DEPLOYMENT"])


def optimize_prompt(raw: str) -> str:
    if _rewrite_client is None:
        return raw

    try:
        messages = [
            {"role": "system", "content": _REWRITE_SYSTEM_INSTRUCTION},
            {"role": "user", "content": raw},
        ]
        # Debug-log the payload sent to the rewrite model
        logging.debug("Rewrite model request | endpoint=%s deployment=%s\n%s",
                      os.environ.get("AZURE_REWRITE_ENDPOINT"),
                      os.environ.get("AZURE_REWRITE_DEPLOYMENT"),
                      json.dumps(messages, ensure_ascii=False, indent=2))

        result = _rewrite_client.chat.completions.create(
            model=os.environ["AZURE_REWRITE_DEPLOYMENT"],
            messages=messages,
            max_tokens=REWRITE_MAX_TOKENS,
            temperature=0.0,
        )
        optimized = (result.choices[0].message.content or "").strip()
        logging.debug("Rewrite model response: %r", optimized)
        if not optimized:
            logging.warning("Rewrite model returned empty response – using original message.")
            return raw
        logging.info("Prompt optimised | original=%r | optimised=%r", raw, optimized)
        return optimized
    except OpenAIError as exc:
        logging.warning("Prompt optimisation failed (%s) – using original message.", exc)
        return raw


async def fetch_context(query: str, model: Optional[str] = None, timeout: float = 3.0) -> Optional[str]:
    """Call the external Context_Handler HTTP service to retrieve relevant context.

    Returns the context string on success or None on error / if service not configured.
    """
    if not CONTEXT_HANDLER_URL or not CONTEXT_HANDLER_TOKEN:
        logging.debug("Context handler not configured (URL/token missing) – skipping context fetch.")
        return None

    headers = {
        "Authorization": f"Bearer {CONTEXT_HANDLER_TOKEN}",
        "Content-Type": "application/json",
    }

    payload = {"query": query}
    if model:
        payload["model"] = model

    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            logging.debug("Calling Context_Handler %s with payload: %s", CONTEXT_HANDLER_URL, payload)
            resp = await client.post(CONTEXT_HANDLER_URL, headers=headers, json=payload)
        logging.debug("Context_Handler response status: %s", resp.status_code)
        if resp.status_code != 200:
            logging.warning("Context handler returned non-200 status %s: %s", resp.status_code, resp.text)
            return None
        data = resp.json()
        context = data.get("context")
        if context is None:
            logging.warning("Context handler response missing 'context' field: %s", data)
            return None
        # ensure string
        if isinstance(context, list):
            # join list items into a single string
            context = "\n\n".join(map(str, context))
        else:
            context = str(context)
        logging.debug("Retrieved context length=%d", len(context))
        return context
    except httpx.RequestError as exc:
        logging.warning("Context handler request failed: %s", exc)
        return None
    except Exception as exc:
        logging.warning("Unexpected error fetching context: %s", exc)
        return None


@app.post("/api/session/init", response_model=SessionInitResponse)
async def session_init(req: SessionInitRequest) -> SessionInitResponse:
    """Initialise a chat session with the system prompt.

    Creates a new session entry containing only the system prompt message.
    If the session already exists it is left unchanged (idempotent).
    The LLM is **not** called; nothing is shown in the UI.

    Args:
        req: Request body containing the client-generated session ID.

    Returns:
        A ``SessionInitResponse`` with status ``"ok"`` and the session ID.
    """
    if req.sessionId not in _sessions:
        _sessions[req.sessionId] = [{"role": "system", "content": _SYSTEM_PROMPT}]
        logging.info("Session initialised: %s", req.sessionId)
    else:
        logging.info("Session already exists, skipping init: %s", req.sessionId)
    return SessionInitResponse(status="ok", sessionId=req.sessionId)


@app.post("/api/chat", response_model=ChatResponse)
async def chat(req: ChatRequest) -> ChatResponse:
    """Handle a chat request and return an answer from the Azure OpenAI API.

    Maintains full conversation history per session so the LLM has context
    from previous turns. If no session exists yet (e.g. the init endpoint was
    not called) one is created on-the-fly with the system prompt.

    Args:
        req: The incoming request containing the user's message and session ID.

    Returns:
        A ``ChatResponse`` with the generated answer string.
    """
    if _azure_client is None:
        raise HTTPException(
            status_code=503,
            detail="Azure OpenAI client not configured. Set AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_API_KEY and AZURE_OPENAI_DEPLOYMENT.",
        )

    # Ensure the session exists (fallback if /api/session/init was not called)
    if req.sessionId not in _sessions:
        logging.warning("Session %s not found – creating on-the-fly.", req.sessionId)
        _sessions[req.sessionId] = [{"role": "system", "content": _SYSTEM_PROMPT}]

    history = _sessions[req.sessionId]

    # 1) Try fetching context from the Context_Handler service (optional)
    try:
        context_text = await fetch_context(req.message, model=req.model)
    except Exception as e:
        logging.warning("Error while fetching context: %s", e)
        context_text = None

    if context_text:
        # Insert the returned context right after the system prompt so the model sees it
        # without overwriting the main system instruction.
        logging.debug("Inserting retrieved context into history (len=%d)", len(context_text))
        history.insert(1, {"role": "system", "content": f"Retrieved context:\n{context_text}"})

    # 2) Run the lightweight prompt optimiser (if configured) and append the user's message
    optimized_message = optimize_prompt(req.message)
    history.append({"role": "user", "content": optimized_message})

    # Log full history that will be sent to main model
    logging.debug("LLM request messages (full history):\n%s", json.dumps(history, ensure_ascii=False, indent=2))

    try:
        completion = _azure_client.chat.completions.create(
            model=os.environ["AZURE_OPENAI_DEPLOYMENT"],
            messages=history,
            max_tokens=MAX_TOKENS,
        )
        answer = completion.choices[0].message.content or ""
        history.append({"role": "assistant", "content": answer})
        return ChatResponse(answer=answer)
    except OpenAIError as exc:
        # Remove the user message that failed so the history stays consistent
        history.pop()
        raise HTTPException(status_code=502, detail="Azure OpenAI request failed.") from exc

# ensure debug logs go to the terminal
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
# also set uvicorn loggers to DEBUG so their output is visible
for name in ("uvicorn", "uvicorn.error", "uvicorn.access"):
    logging.getLogger(name).setLevel(logging.DEBUG)


